
package Requerimientos;

import Clases.Producto;
import Cllases.BO.ProductoBO;
import Presentacion.Femmie;
import javax.swing.JOptionPane;

public class FormularioProductos extends javax.swing.JFrame {

    /**
     * Creates new form FormularioProductos
     */
    private ProductoBO pBO = new ProductoBO();
    public FormularioProductos() {
        initComponents();
        listarProducto();
        this.setLocationRelativeTo(null);

    }
    
    public void listarProducto()
    {
        pBO.listarProducto(dbformularioproductos);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtseccionproducto = new javax.swing.JTextField();
        txtskuproducto = new javax.swing.JTextField();
        txtcategoriaproducto = new javax.swing.JTextField();
        txtlineaproducto = new javax.swing.JTextField();
        txtmodeloproducto = new javax.swing.JTextField();
        txtcolorproducto = new javax.swing.JTextField();
        txtpreciounitarioproducto = new javax.swing.JTextField();
        txtmedidaproducto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        dbformularioproductos = new javax.swing.JTable();
        btnagregarproducto = new javax.swing.JButton();
        btneliminarproducto = new javax.swing.JButton();
        btnmodificarproducto = new javax.swing.JButton();
        btnlimpiarproductos = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Formulario Productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 58, -1, 37));

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel6.setText("SKU");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel7.setText("Sección");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel8.setText("Categoría");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 167, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel9.setText("Línea");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel10.setText("Modelo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 219, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel11.setText("Color");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, -1, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel12.setText("Medida");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 271, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel13.setText("Precio Unitario");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 297, -1, -1));
        getContentPane().add(txtseccionproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 139, 230, -1));
        getContentPane().add(txtskuproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 113, 230, -1));

        txtcategoriaproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcategoriaproductoActionPerformed(evt);
            }
        });
        getContentPane().add(txtcategoriaproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 165, 230, -1));
        getContentPane().add(txtlineaproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 191, 230, -1));
        getContentPane().add(txtmodeloproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 217, 230, -1));
        getContentPane().add(txtcolorproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 243, 230, -1));
        getContentPane().add(txtpreciounitarioproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 295, 230, -1));
        getContentPane().add(txtmedidaproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 269, 230, -1));

        dbformularioproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        dbformularioproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbformularioproductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dbformularioproductos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 58, 695, 362));

        btnagregarproducto.setBackground(new java.awt.Color(255, 204, 204));
        btnagregarproducto.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        btnagregarproducto.setText("Añadir  Producto");
        btnagregarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarproductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregarproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 344, -1, -1));

        btneliminarproducto.setBackground(new java.awt.Color(255, 204, 204));
        btneliminarproducto.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        btneliminarproducto.setText("Eliminar");
        btneliminarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarproductoActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminarproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 344, -1, -1));

        btnmodificarproducto.setBackground(new java.awt.Color(255, 204, 204));
        btnmodificarproducto.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        btnmodificarproducto.setText("Modificar");
        btnmodificarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarproductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodificarproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 387, -1, -1));

        btnlimpiarproductos.setBackground(new java.awt.Color(255, 204, 204));
        btnlimpiarproductos.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        btnlimpiarproductos.setText("Limpiar");
        btnlimpiarproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarproductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiarproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 387, -1, -1));

        btnsalir.setBackground(new java.awt.Color(255, 153, 153));
        btnsalir.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        btnsalir.setText("Volver");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1094, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEDA.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 490, 440));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel5.setText("Inicio  >  Producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEDA.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 440));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEDA.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 490, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcategoriaproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcategoriaproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcategoriaproductoActionPerformed

    private void btnagregarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarproductoActionPerformed
        // TODO add your handling code here:
        if(txtskuproducto.getText().isEmpty()||txtseccionproducto.getText().isEmpty()
                 ||txtcategoriaproducto.getText().isEmpty()||txtlineaproducto.getText().isEmpty()
                 ||txtmodeloproducto.getText().isEmpty()||txtcolorproducto.getText().isEmpty()
                 ||txtmedidaproducto.getText().isEmpty()||txtpreciounitarioproducto.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }
        else
        {
            Producto pro = new Producto();
            pro.setSKU(txtskuproducto.getText());
            pro.setSeccion(txtseccionproducto.getText());
            pro.setCategoria(txtcategoriaproducto.getText());
            pro.setLinea(txtlineaproducto.getText());
            pro.setModelo(txtmodeloproducto.getText());
            pro.setColor(txtcolorproducto.getText());
            pro.setMedida(txtmedidaproducto.getText());
            pro.setPrecioUnitario(Integer.parseInt(txtpreciounitarioproducto.getText()));
            
            String mensaje = pBO.agregarProducto(pro);
            
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarProducto();
        }
    }//GEN-LAST:event_btnagregarproductoActionPerformed

    private void btneliminarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarproductoActionPerformed
        // TODO add your handling code here:
        if(txtskuproducto.getText().isEmpty()||txtseccionproducto.getText().isEmpty()||txtcategoriaproducto.getText().isEmpty()||txtlineaproducto.getText().isEmpty()||txtmodeloproducto.getText().isEmpty()||txtcolorproducto.getText().isEmpty()||txtmedidaproducto.getText().isEmpty()||txtpreciounitarioproducto.getText().isEmpty())
        {JOptionPane.showMessageDialog(null, "Llene todos los campos");}
        else
        {
            String mensaje = pBO.eliminarProducto(Integer.parseInt(txtskuproducto.getText()));
            JOptionPane.showMessageDialog(null,mensaje);
            limpiar();
            listarProducto();
        }
    }//GEN-LAST:event_btneliminarproductoActionPerformed

    private void btnmodificarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarproductoActionPerformed
        // TODO add your handling code here:
        if(txtskuproducto.getText().isEmpty()||txtseccionproducto.getText().isEmpty()||txtcategoriaproducto.getText().isEmpty()||txtlineaproducto.getText().isEmpty()||txtmodeloproducto.getText().isEmpty()||txtcolorproducto.getText().isEmpty()||txtmedidaproducto.getText().isEmpty()||txtpreciounitarioproducto.getText().isEmpty())
        {JOptionPane.showMessageDialog(null, "Llene todos los campos");}
        else
        {
            Producto pro = new Producto();
            pro.setSKU(txtskuproducto.getText());
            pro.setSeccion(txtseccionproducto.getText());
            pro.setCategoria(txtcategoriaproducto.getText());
            pro.setLinea(txtlineaproducto.getText());
            pro.setModelo(txtmodeloproducto.getText());
            pro.setColor(txtcolorproducto.getText());
            pro.setMedida(txtmedidaproducto.getText());
            pro.setPrecioUnitario(Integer.parseInt(txtpreciounitarioproducto.getText()));
            String mensaje = pBO.modificarProducto(pro);
            JOptionPane.showMessageDialog(null,mensaje);
            limpiar();
            listarProducto();
        }
    }//GEN-LAST:event_btnmodificarproductoActionPerformed

    private void btnlimpiarproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarproductosActionPerformed
        // TODO add your handling code here:
        limpiar();       
    }//GEN-LAST:event_btnlimpiarproductosActionPerformed

    public void limpiar()
    {
        txtskuproducto.setText("");
        txtseccionproducto.setText("");
        txtcategoriaproducto.setText("");
        txtlineaproducto.setText("");
        txtmodeloproducto.setText("");
        txtcolorproducto.setText("");
        txtmedidaproducto.setText("");
        txtpreciounitarioproducto.setText(""); 
    }
    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        
        Femmie volver = new Femmie();
        volver.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnsalirActionPerformed

    private void dbformularioproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbformularioproductosMouseClicked
        // TODO add your handling code here:
        int seleccion = dbformularioproductos.rowAtPoint(evt.getPoint());
        txtskuproducto.setText(dbformularioproductos.getValueAt(seleccion, 0)+"");
        txtseccionproducto.setText(dbformularioproductos.getValueAt(seleccion, 1)+"");
        txtcategoriaproducto.setText(dbformularioproductos.getValueAt(seleccion, 2)+"");
        txtlineaproducto.setText(dbformularioproductos.getValueAt(seleccion, 3)+"");
        txtmodeloproducto.setText(dbformularioproductos.getValueAt(seleccion, 4)+"");
        txtcolorproducto.setText(dbformularioproductos.getValueAt(seleccion, 5)+"");
        txtmedidaproducto.setText(dbformularioproductos.getValueAt(seleccion, 6)+"");
        txtpreciounitarioproducto.setText(dbformularioproductos.getValueAt(seleccion, 7)+""); 
        
    }//GEN-LAST:event_dbformularioproductosMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregarproducto;
    private javax.swing.JButton btneliminarproducto;
    private javax.swing.JButton btnlimpiarproductos;
    private javax.swing.JButton btnmodificarproducto;
    private javax.swing.JButton btnsalir;
    private javax.swing.JTable dbformularioproductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcategoriaproducto;
    private javax.swing.JTextField txtcolorproducto;
    private javax.swing.JTextField txtlineaproducto;
    private javax.swing.JTextField txtmedidaproducto;
    private javax.swing.JTextField txtmodeloproducto;
    private javax.swing.JTextField txtpreciounitarioproducto;
    private javax.swing.JTextField txtseccionproducto;
    private javax.swing.JTextField txtskuproducto;
    // End of variables declaration//GEN-END:variables
}
