
package Requerimientos;

import Clases.Pedido;
import Cllases.BO.PedidoBO;
import Presentacion.Femmie;
import javax.swing.JOptionPane;


public class FormularioPedidos extends javax.swing.JFrame {

    /**
     * Creates new form AgregarProductos
     */
    
    public PedidoBO pedBO = new PedidoBO();
    
    public FormularioPedidos() {
        initComponents();
        listarPedido();
        this.setLocationRelativeTo(null);
    }
    public void listarPedido()
    {
        pedBO.listarPedido(jTablePedido);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoDelivery = new javax.swing.ButtonGroup();
        GrupoPromocion = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextPedido = new javax.swing.JTextField();
        jButtonRegistrar = new javax.swing.JButton();
        jBCerrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFechaE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedido = new javax.swing.JTable();
        jButtonEliminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButtonRelacion = new javax.swing.JButton();
        jTextFechaR = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBoxDelivery = new javax.swing.JComboBox();
        jComboBoxPromocion = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel15 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEDA.jpg"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEDA.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("Formulario Pedido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 330, 40));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel3.setText("N° Pedido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel6.setText("Promoción");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 90, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel7.setText("Delivery");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 80, -1));

        jTextPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 130, -1));

        jButtonRegistrar.setBackground(new java.awt.Color(255, 204, 204));
        jButtonRegistrar.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jBCerrar.setBackground(new java.awt.Color(255, 153, 153));
        jBCerrar.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jBCerrar.setText("Volver");
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 80, 30));

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel8.setText("Fecha Entrega");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, -1));

        jTextFechaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFechaEActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFechaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 130, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel9.setText("Inicio   >  Pedido ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePedido);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 610, 400));

        jButtonEliminar.setBackground(new java.awt.Color(255, 204, 204));
        jButtonEliminar.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 100, 30));

        jLabel11.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel11.setText("Fecha registro");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, -1));

        jButtonRelacion.setBackground(new java.awt.Color(255, 204, 204));
        jButtonRelacion.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonRelacion.setText("Datos Cliente");
        jButtonRelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 140, -1));

        jTextFechaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFechaRActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFechaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 130, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEDA.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 460, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButton1.setText("Añadir Producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        jComboBoxDelivery.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---------------", "PEDIDOS YA", "GLOBO", "RAPPI" }));
        getContentPane().add(jComboBoxDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jComboBoxPromocion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----------------------", "PROM15OFF", "PROM30OFF", "PROMMSG", "MOTHERSDAY2021" }));
        getContentPane().add(jComboBoxPromocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEDA.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEDA.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 520, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPedidoActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        // TODO add your handling code here:
         
        Femmie salir = new Femmie();
        salir.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jBCerrarActionPerformed

    private void jTextFechaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFechaEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFechaEActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        
        if ( jTextPedido.getText().isEmpty() 
                || jTextFechaR.getText().isEmpty() ) 
        {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos.");
        }
        else
        {
            Pedido ped = new Pedido();
           
            ped.setNumPedido(jTextPedido.getText());
            ped.setFechaRegistro(jTextFechaR.getText());
            ped.setFechaEntrega(jTextFechaE.getText());
 
            // DELIVERY
            if(jComboBoxDelivery.getSelectedIndex() == 1)
            {
                ped.setCodDelivery((String) jComboBoxDelivery.getSelectedItem());
            }
            
            else if(jComboBoxDelivery.getSelectedIndex() == 2)
            {
                ped.setCodDelivery((String) jComboBoxDelivery.getSelectedItem());
            }
            
            else if(jComboBoxDelivery.getSelectedIndex() == 3)
            {
                ped.setCodDelivery((String) jComboBoxDelivery.getSelectedItem());
            }
            
            else
            {
                ped.setCodDelivery(null);
            }
            
            // PROMOCION
            if(jComboBoxPromocion.getSelectedIndex() == 1)
            {
                ped.setNumPromocion((String) jComboBoxPromocion.getSelectedItem());
            }
            
            else if(jComboBoxPromocion.getSelectedIndex() == 2)
            {
                ped.setNumPromocion((String) jComboBoxPromocion.getSelectedItem());
            }
            
            else if(jComboBoxPromocion.getSelectedIndex() == 3)
            {
                ped.setNumPromocion((String) jComboBoxPromocion.getSelectedItem());
            }
            
            else if(jComboBoxPromocion.getSelectedIndex() == 4)
            {
                ped.setNumPromocion((String) jComboBoxPromocion.getSelectedItem());
            }
            
            else
            {
                ped.setNumPromocion(null);
            }
            
            String mensaje = pedBO.registrarPedido(ped);
            
            JOptionPane.showMessageDialog(null, mensaje);
            borrar();
            listarPedido();
        }
        
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jTextFechaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFechaRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFechaRActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        if (jTextPedido.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos.");
        }
        else
        {            
            String mensaje = pedBO.eliminarPedido(jTextPedido.getText());
            JOptionPane.showMessageDialog(null, mensaje);
            borrar();
            listarPedido();
        }
        
        
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTablePedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePedidoMouseClicked
        // TODO add your handling code here:
         int seleccion = jTablePedido.rowAtPoint(evt.getPoint());
        jTextPedido.setText(jTablePedido.getValueAt(seleccion, 0)+"");
        jComboBoxPromocion.setSelectedItem(jTablePedido.getValueAt(seleccion, 1));
        jComboBoxDelivery.setSelectedItem(jTablePedido.getValueAt(seleccion, 2));
        jTextFechaR.setText(jTablePedido.getValueAt(seleccion, 3)+"");
        jTextFechaE.setText(jTablePedido.getValueAt(seleccion, 4)+"");
        
        
        
    }//GEN-LAST:event_jTablePedidoMouseClicked

    private void jButtonRelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelacionActionPerformed
        // TODO add your handling code here:
        RelacionPedidoCliente agregar = new RelacionPedidoCliente();
        agregar.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonRelacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RelacionContProd agregar = new RelacionContProd();
        agregar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoDelivery;
    private javax.swing.ButtonGroup GrupoPromocion;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonRelacion;
    private javax.swing.JComboBox jComboBoxDelivery;
    private javax.swing.JComboBox jComboBoxPromocion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablePedido;
    private javax.swing.JTextField jTextFechaE;
    private javax.swing.JTextField jTextFechaR;
    private javax.swing.JTextField jTextPedido;
    // End of variables declaration//GEN-END:variables

    private void borrar() {
       
        jTextPedido.setText("");
        jTextFechaR.setText("");
        jTextFechaE.setText("");
        jComboBoxDelivery.setSelectedIndex(0);
        jComboBoxPromocion.setSelectedIndex(0);
    }
}
