
package Requerimientos;

import Clases.Cliente;
import Clases.Telefono;
import Cllases.BO.ClienteBO;
import Presentacion.Femmie;
import javax.swing.JOptionPane;


public class FormularioCliente extends javax.swing.JFrame {

    /**
     * Creates new form FormularioCliente
     */
    public ClienteBO cliBO = new ClienteBO();
    
    public FormularioCliente() {
        initComponents();
        listarCliente();
        this.setLocationRelativeTo(null);
        //DNIMax();
    }
    
    public void listarCliente()
    {
        cliBO.listarCliente(jTableCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNombre = new javax.swing.JLabel();
        jTitulo = new javax.swing.JLabel();
        jCorreo = new javax.swing.JLabel();
        jDNI = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextCorreo = new javax.swing.JTextField();
        jTextDNI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jButtonSalir = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jDireccion = new javax.swing.JLabel();
        jTextDireccion = new javax.swing.JTextField();
        jButtonTelefono = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jNombre.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jNombre.setText("Nombre");
        getContentPane().add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 150, 40));

        jTitulo.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jTitulo.setText("Formulario Cliente");
        getContentPane().add(jTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 300, 40));

        jCorreo.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jCorreo.setText("Correo");
        getContentPane().add(jCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, 40));

        jDNI.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jDNI.setText("DNI");
        getContentPane().add(jDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 40));
        getContentPane().add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 200, 30));
        getContentPane().add(jTextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 200, 30));
        getContentPane().add(jTextDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 200, 30));

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 520, 350));

        jButtonSalir.setBackground(new java.awt.Color(255, 153, 153));
        jButtonSalir.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonSalir.setText("Volver");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 80, 30));

        jButtonRegistrar.setBackground(new java.awt.Color(255, 204, 204));
        jButtonRegistrar.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jButtonActualizar.setBackground(new java.awt.Color(255, 204, 204));
        jButtonActualizar.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        jButtonEliminar.setBackground(new java.awt.Color(255, 204, 204));
        jButtonEliminar.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 120, -1));

        jButtonBorrar.setBackground(new java.awt.Color(255, 204, 204));
        jButtonBorrar.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 110, -1));

        jDireccion.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jDireccion.setText("Direccion");
        getContentPane().add(jDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, 40));
        getContentPane().add(jTextDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 200, 30));

        jButtonTelefono.setBackground(new java.awt.Color(255, 204, 204));
        jButtonTelefono.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonTelefono.setText("Registrar Teléfono");
        jButtonTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel3.setText("Inicio   >   Cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEDA.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 470));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEDA.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 510, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        Femmie salir = new Femmie();
        salir.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
        borrar();
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        if (jTextDNI.getText().isEmpty() || jTextNombre.getText().isEmpty() 
                || jTextCorreo.getText().isEmpty() || jTextDireccion.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos.");
        }
        else
        {
            Cliente cli = new Cliente();
            //Telefono tel = new Telefono();
            cli.setDNI(jTextDNI.getText());
            cli.setNombre(jTextNombre.getText());
            cli.setCorreo(jTextCorreo.getText());
            cli.setDireccion(jTextDireccion.getText());
            //cli.setTelefono(Integer.parseInt(jTextTelefono.getText()));
            
            String mensaje = cliBO.registrarCliente(cli);
            
            JOptionPane.showMessageDialog(null, mensaje);
            borrar();
            listarCliente();
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
        if (jTextDNI.getText().isEmpty() || jTextNombre.getText().isEmpty() 
                || jTextCorreo.getText().isEmpty() || jTextDireccion.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos.");
        }
        else
        {
            Cliente cli = new Cliente();
            //Telefono tel = new Telefono();
            cli.setDNI(jTextDNI.getText());
            cli.setNombre(jTextNombre.getText());
            cli.setCorreo(jTextCorreo.getText());
            cli.setDireccion(jTextDireccion.getText());
            //tel.setTelefono_Cliente(Integer.parseInt(jTextTelefono.getText()));
            
            String mensaje = cliBO.actualizarCliente(cli);
            
            JOptionPane.showMessageDialog(null, mensaje);
            borrar();
            listarCliente();
        }
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        if (jTextDNI.getText().isEmpty() || jTextNombre.getText().isEmpty() 
                || jTextCorreo.getText().isEmpty() || jTextDireccion.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos.");
        }
        else
        {            
            String mensaje = cliBO.eliminarCliente(jTextDNI.getText());
            JOptionPane.showMessageDialog(null, mensaje);
            borrar();
            listarCliente();
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        // TODO add your handling code here:
        int seleccion = jTableCliente.rowAtPoint(evt.getPoint());
        jTextDNI.setText(jTableCliente.getValueAt(seleccion, 0)+"");
        jTextNombre.setText(jTableCliente.getValueAt(seleccion, 1)+"");
        jTextCorreo.setText(jTableCliente.getValueAt(seleccion, 2)+"");
        jTextDireccion.setText(jTableCliente.getValueAt(seleccion, 3)+"");
        //jTextTelefono.setText(jTableCliente.getValueAt(seleccion, 4)+"");
    
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void jButtonTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelefonoActionPerformed
        // TODO add your handling code here:
        RelacionTelefonoCliente entrar = new RelacionTelefonoCliente();
        entrar.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButtonTelefonoActionPerformed

    public void borrar()
    {
        jTextDNI.setText("");
        jTextNombre.setText("");
        jTextCorreo.setText("");
        jTextDireccion.setText("");
        //jTextBuscar.setText("");
        //jTextTelefono.setText("");
        //DNIMax();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonTelefono;
    private javax.swing.JLabel jCorreo;
    private javax.swing.JLabel jDNI;
    private javax.swing.JLabel jDireccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextDNI;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration//GEN-END:variables
}
