
package Requerimientos;
import Clases.Pedido;
import Cllases.BO.PedidoBO;
import javax.swing.JOptionPane;

public class RelacionPedidoCliente extends javax.swing.JFrame {

    /**
     * Creates new form RelacionPedidoCliente
     */
    public PedidoBO pedBO = new PedidoBO();
    public RelacionPedidoCliente() {
        initComponents();
        listarPedidoCliente();
        this.setLocationRelativeTo(null);
    }
     public void listarPedidoCliente()
    {
        pedBO.listarPedidoCliente(jTableRelacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Cerrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextPedido = new javax.swing.JTextField();
        jTextDni = new javax.swing.JTextField();
        jTextEstado = new javax.swing.JTextField();
        jTextTarjeta = new javax.swing.JTextField();
        jTextCuenta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRelacion = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel1.setText("Numero de Pedido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 134, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel2.setText("DNI de cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 181, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel3.setText("Estado del Pedido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 234, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel4.setText("Tarjeta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 282, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel5.setText("N° Cuenta");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 330, -1, -1));

        Cerrar.setBackground(new java.awt.Color(255, 153, 153));
        Cerrar.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        Cerrar.setText("Volver");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 0, 93, -1));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 397, 106, -1));

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 397, 104, -1));
        getContentPane().add(jTextPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 132, 103, -1));

        jTextDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDniActionPerformed(evt);
            }
        });
        getContentPane().add(jTextDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 179, 103, -1));
        getContentPane().add(jTextEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 232, 103, -1));
        getContentPane().add(jTextTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 280, 103, -1));
        getContentPane().add(jTextCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 328, 103, -1));

        jTableRelacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableRelacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRelacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRelacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 49, -1, 366));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel6.setText("Datos Cliente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEDA.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 460, 450));

        jLabel9.setText("Inicio   >  Pedido  >  Registrar Datos Cliente");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEDA.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDniActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        // TODO add your handling code here:
        
        FormularioPedidos salir = new FormularioPedidos();
        salir.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_CerrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
         if ( jTextPedido.getText().isEmpty() ) 
        {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos.");
        }
        else
        {
            Pedido ped = new Pedido();
           
           ped.setNumPedido(jTextPedido.getText());
           
           ped.setDni(jTextDni.getText());
           ped.setEstadoPedido(jTextEstado.getText());
           ped.setTarjeta(jTextTarjeta.getText());
           ped.setNumeroTarjeta(jTextCuenta.getText());
           String mensaje = pedBO.registrarPedidoCliente(ped);
            
            JOptionPane.showMessageDialog(null, mensaje);
            borrar();
            listarPedidoCliente();
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTableRelacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRelacionMouseClicked
        // TODO add your handling code here:
        
        
       int seleccion = jTableRelacion.rowAtPoint(evt.getPoint());
       jTextPedido.setText(jTableRelacion.getValueAt(seleccion, 0)+"");
       jTextDni.setText(jTableRelacion.getValueAt(seleccion, 1)+"");
       jTextEstado.setText(jTableRelacion.getValueAt(seleccion, 2)+"");
       jTextTarjeta.setText(jTableRelacion.getValueAt(seleccion, 3)+"");
       jTextCuenta.setText(jTableRelacion.getValueAt(seleccion, 4)+"");
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jTableRelacionMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        if (jTextPedido.getText().isEmpty() 
                 ) 
        {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos.");
        }
        else
        {            
            String mensaje = pedBO.eliminarPedidoCliente(jTextPedido.getText() );
            JOptionPane.showMessageDialog(null, mensaje);
            borrar();
            listarPedidoCliente();
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

   

     public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelacionPedidoCliente().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRelacion;
    private javax.swing.JTextField jTextCuenta;
    private javax.swing.JTextField jTextDni;
    private javax.swing.JTextField jTextEstado;
    private javax.swing.JTextField jTextPedido;
    private javax.swing.JTextField jTextTarjeta;
    // End of variables declaration//GEN-END:variables

    private void borrar() {
        jTextPedido.setText("");
        jTextDni.setText("");
        jTextEstado.setText("");
        jTextTarjeta.setText("");
        jTextCuenta.setText("");
        


    }

   
}
