
package Requerimientos;
import Clases.Cliente;
import Clases.Telefono;
import Cllases.BO.ClienteBO;
import Presentacion.Femmie;
import javax.swing.JOptionPane;
/**
 *
 * @author DUEÑAS
 */
public class RelacionTelefonoCliente extends javax.swing.JFrame {

    /**
     * Creates new form RelacionTelefonoCliente
     */
    
     public ClienteBO cliBO = new ClienteBO();
    public RelacionTelefonoCliente() {
        initComponents();
        listarTelefono();
        this.setLocationRelativeTo(null);
        
    }
         public void listarTelefono()
    {
        cliBO.listarTelefono(jTableTelefono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTelefono = new javax.swing.JTable();
        jTextDNI = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel1.setText("DNI  del  cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        jLabel2.setText("Teléfono");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jTableTelefono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTelefonoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTelefono);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 320, 260));

        jTextDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDNIActionPerformed(evt);
            }
        });
        getContentPane().add(jTextDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 152, -1));
        getContentPane().add(jTextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 152, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel3.setText("Registro de Teléfono");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 80, 30));

        jButtonAgregar.setBackground(new java.awt.Color(255, 204, 204));
        jButtonAgregar.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 100, -1));

        jButtonEliminar.setBackground(new java.awt.Color(255, 204, 204));
        jButtonEliminar.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 100, -1));

        jButtonModificar.setBackground(new java.awt.Color(255, 204, 204));
        jButtonModificar.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel5.setText("Inicio   >   Cliente  >  Registrar Teléfono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEDA.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 490, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        if (jTextDNI.getText().isEmpty() || jTextDNI.getText().isEmpty() 
                ) 
        {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos.");
        }
        else
        {
            //Cliente cli = new Cliente();
            Telefono tel = new Telefono();
            tel.setDNI(jTextDNI.getText());
            tel.setTelefono_Cliente(jTextTelefono.getText() );
           
            
            String mensaje = cliBO.registrarTelefono(tel);
            
            JOptionPane.showMessageDialog(null, mensaje);
            borrar();
            listarTelefono();
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        
         if (jTextDNI.getText().isEmpty() || jTextDNI.getText().isEmpty() 
                ) 
        {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos.");
        }
        else
        {

            
              Cliente tel = new Cliente();
            tel.setDNI(jTextDNI.getText());
            tel.setTelefono(jTextTelefono.getText() );
           
            
            String mensaje = cliBO.actualizarTelefono(tel);
            
            JOptionPane.showMessageDialog(null, mensaje);
            borrar();
            listarTelefono();
        }
        
        
        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
         if (jTextDNI.getText().isEmpty() || jTextDNI.getText().isEmpty() 
                ) 
        {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos.");
        }
        else
        {            
            String mensaje = cliBO.eliminarCliente(jTextDNI.getText());
            JOptionPane.showMessageDialog(null, mensaje);
            borrar();
            listarTelefono();
        }
        
        
        
        
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTableTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTelefonoMouseClicked
        // TODO add your handling code here:
        
         int seleccion = jTableTelefono.rowAtPoint(evt.getPoint());
        jTextDNI.setText(jTableTelefono.getValueAt(seleccion, 0)+"");
        jTextTelefono.setText(jTableTelefono.getValueAt(seleccion, 1)+"");
        
        
        
    }//GEN-LAST:event_jTableTelefonoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormularioCliente salir = new FormularioCliente();
        salir.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDNIActionPerformed

    public void borrar()
    {
        jTextDNI.setText("");

        jTextTelefono.setText("");
        //DNIMax();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelacionTelefonoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelacionTelefonoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelacionTelefonoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelacionTelefonoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelacionTelefonoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTelefono;
    private javax.swing.JTextField jTextDNI;
    private javax.swing.JTextField jTextTelefono;
    // End of variables declaration//GEN-END:variables

 
   
}
