
package Presentacion;



import DAO.PedidoDAO;
import Requerimientos.FormularioCliente;
import Requerimientos.FormularioPedidos;
import Cllases.BO.PedidoBO;
import Requerimientos.FormularioProductos;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Femmie extends javax.swing.JFrame {

    /**
     * Creates new form Femmie
     */
    public PedidoDAO ped = new PedidoDAO();
    public Femmie() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelAgregar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelAgregarPedido = new javax.swing.JLabel();
        jButtonPedido = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jButtonMontoFinal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelAgregarPedido1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonPedido1 = new javax.swing.JButton();
        jTextMonto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("Femmie");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, 60));

        jLabelAgregar.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabelAgregar.setText("Cliente");
        getContentPane().add(jLabelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButton1.setText("Agregar Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));

        jLabelAgregarPedido.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabelAgregarPedido.setText("Producto");
        getContentPane().add(jLabelAgregarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jButtonPedido.setBackground(new java.awt.Color(255, 204, 204));
        jButtonPedido.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonPedido.setText("Agregar Pedido");
        jButtonPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jButtonCerrar.setBackground(new java.awt.Color(255, 153, 153));
        jButtonCerrar.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 80, -1));

        jButtonMontoFinal.setBackground(new java.awt.Color(255, 204, 204));
        jButtonMontoFinal.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonMontoFinal.setText("Ver Monto Fiinal");
        jButtonMontoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMontoFinalActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMontoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 170, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel4.setText("Inicio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelAgregarPedido1.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabelAgregarPedido1.setText("Pedido");
        getContentPane().add(jLabelAgregarPedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel2.setText("N° de Pedido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 130, -1));

        jButtonPedido1.setBackground(new java.awt.Color(255, 204, 204));
        jButtonPedido1.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        jButtonPedido1.setText("Agregar Producto");
        jButtonPedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedido1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));
        getContentPane().add(jTextMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 160, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEDA.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormularioCliente agregar = new FormularioCliente();
        agregar.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedidoActionPerformed
        // TODO add your handling code here:
        FormularioPedidos agregar = new FormularioPedidos();
        agregar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPedidoActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonMontoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMontoFinalActionPerformed
        

        try {
          
            JOptionPane.showMessageDialog(null, ped.obtenerMonto(jTextMonto.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Intente con otro Monto");
        }
    
    }//GEN-LAST:event_jButtonMontoFinalActionPerformed

    private void jButtonPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedido1ActionPerformed
        // TODO add your handling code here:
        
        
        FormularioProductos agregar = new FormularioProductos();
        agregar.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButtonPedido1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Femmie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Femmie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Femmie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Femmie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Femmie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonMontoFinal;
    private javax.swing.JButton jButtonPedido;
    private javax.swing.JButton jButtonPedido1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAgregar;
    private javax.swing.JLabel jLabelAgregarPedido;
    private javax.swing.JLabel jLabelAgregarPedido1;
    private javax.swing.JTextField jTextMonto;
    // End of variables declaration//GEN-END:variables
}
